### ISSUE TITLE
Feature request: "volume_up" 

### ISSUE THREAD

**Issue by 3SCadmin** [dart-tools/flutter_android_volume_keydown#1]
Hi,

First:  Thank you for this package!
I have tried pretty much every flutter package that claims to perform this task: NONE of them worked.

But yours works!

My feature request:
Could you add the ability to also detect the Volume_Up Key?
I'm playing with one of those bluetooth remote camera shutter things  [link](https://www.amazon.co.uk/Ailun-Bluetooth-Smartphone-Compatible-Included-Black/dp/B06XD9GZ3T/ref=asc_df_B06XD9GZ3T/?tag=googshopuk-21&linkCode=df0&hvadid=311016054675&hvpos=&hvnetw=g&hvrand=17178571955647964334&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9044987&hvtargid=pla-597377135735&psc=1)
It's hardwired to sending a Volume_Up keypress.

**Comment by jgoyvaerts** [comment]
Glad it works for you. I expected this feature request, I quickly just put this together because I only needed the volume down button. I'll see if I can add it in a day or two.
