### ISSUE TITLE
is it necessary to  extend     FlutterAndroidVolumeKeydownActivity

### ISSUE THREAD

**Issue by Manishmg3994** [dart-tools/flutter_android_volume_keydown#2]
Change your MainActivity.java or MainActivity.kt to extend FlutterAndroidVolumeKeydownActivity
i think this is not a necessary

**Comment by jgoyvaerts** [comment]
Not sure why you would think it's not necessary, but if you don't extend the Activity, it doesn't work.

Feel free to correct me if I'm wrong, but provide some proof please.
