### ISSUE TITLE
how should i config MainActivity.kt??? plz helppp

### ISSUE THREAD

**Issue by Lord-A2K** [dart-tools/flutter_android_volume_keydown#5]
how can i configur the app, im new and this plugin not working

**Comment by ARA-ZET** [comment]
i how you will find this helpfull 
package com.example.clmgpx

import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import dev.darttools.flutter_android_volume_keydown.FlutterAndroidVolumeKeydownActivity





class MainActivity : FlutterAndroidVolumeKeydownActivity() {}

**Comment by fyxtc** [comment]
@ARA-ZET Helpful, thank you
